apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::938805821386:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-WUNLVW71R2SP
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::938805821386:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-06T22:48:17Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1820"
  uid: 924d17d2-3753-4966-824e-7dfb3785db5f
